# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

driver = webdriver.Firefox()
driver.get("https://www.lavoixdunord.fr/")
driver.set_window_size(1559, 940)
driver.find_element(By.ID, "didomi-notice-agree-button").click()
driver.find_element(By.LINK_TEXT,
                    "Le gynécologue d’Arras soupçonné de viols et agressions sexuelles radié de l’Ordre des médecins").click()
time.sleep(1.5)
title = driver.title
uri = driver.execute_script("return window.location.href")
driver.back()
print(title)
print(uri)
driver.find_element(By.LINK_TEXT, "Calais : un important réseau de passeurs démantelé en Allemagne").click()
time.sleep(1.5)
title = driver.title
uri = driver.execute_script("return window.location.href")
driver.back()
print(title)
print(uri)
driver.find_element(By.LINK_TEXT,
                    "Personnalisables et vendues à partir de 3 900 €, ces mini-voitures révolutionnent l’électrique en Chine").click()
time.sleep(1.5)
title = driver.title
uri = driver.execute_script("return window.location.href")
driver.back()
print(title)
print(uri)
driver.find_element(By.LINK_TEXT,
                    "Wimille : deux accidents sur l’A16, neuf véhicules impliqués et plusieurs blessés").click()
time.sleep(1.5)
title = driver.title
uri = driver.execute_script("return window.location.href")
driver.back()
print(title)
print(uri)
driver.find_element(By.LINK_TEXT,
                    "Ligue Europa Conférence : le LOSC affrontera Sturm Graz en huitième de finale").click()
time.sleep(1.5)
title = driver.title
uri = driver.execute_script("return window.location.href")
driver.back()
print(title)
print(uri)
